# Welcome to Jekyll!

# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mila GFN Workshop
tagline: A 3-day free workshop on GFlowNets at Mila in Montreal
email: gflownet.workshop@mila.quebec
twitter_username: Mila_Quebec
github_username: GFNOrg
twitter:
  - username: Mila_Quebec
description: A 3-day free workshop on GFlowNets at Mila in Montreal
author: Mila
baseurl: ""
url: ""
logo: assets/img/logo/2023_GFlowNet_logo_Color.png
favicon: assets/img/logo/2023_GFlowNet_logo_White.png

# Reading Files
include:
  - _pages

# Collections
collections:
  playground:
    output: true
    permalink: /:collection/:path/
#   collection2:
#     output: true
#     permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page
      hero_image: ./assets/img/hero/molecules-toy-unsplash-5040x2366-mauve-90dpi.png

# defaults:
#   - scope:
#       path: ""
#       type: "collection1"
#     values:
#       layout: "page"
#   - scope:
#       path: ""
#       type: "collection1"
#     values:
#       layout: "page"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Theme: Bulma Clean Theme
# theme: bulma-clean-theme
remote_theme: chrisrhymes/bulma-clean-theme
